-- migrate:up
CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(200) UNIQUE NOT NULL,
  name VARCHAR(200) NOT NULL,
  password VARCHAR(500) NOT NULL,
  provider_id VARCHAR(300) UNIQUE NOT NULL,
  bank_name VARCHAR(100) NULL,
  bank_account VARCHAR(300) UNIQUE NULL,
  artist_registration VARCHAR(200) UNIQUE NULL,
  bid_agreement BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
)

-- migrate:down
DROP TABLE users;